### ISSUE TITLE
Deploy built sphinx docs

### ISSUE THREAD

**Issue by jrbourbeau** [dask/marketing#2]
We should build and publish the docs in this repo to marketing.dask.org. I'll plan to do this using [`doctr`](https://github.com/drdoctr/doctr) + Travis CI tomorrow unless someone beats me to it

**Comment by mrocklin** [comment]
I tend to use RTD, and would be happy to set it up (it should only take 10
minutes or so).  I'm happy either way though and am fine with doctr if
someone else wants to set that up.

We could also wait on this to see if folks think that we should instead
focus on creating a PDF or some other artifact for this content.  I'm not
sure what is best.  I put this up mostly as a test.

**Comment by jrbourbeau** [comment]
Sure, waiting for more feedback from others seems reasonable
