### ISSUE TITLE
Redirect to marketing.dask.org

### ISSUE THREAD

**Issue by jrbourbeau** [dask/marketing#3]
I'd like to redirect https://dask-marketing.readthedocs.io/en/latest/ to marketing.dask.org. This probably requires some changes to our cloudflare settings. @quasiben did you go through a similar process with your recent work on https://tutorial.dask.org/?

**Comment by quasiben** [comment]
yeah, i can set it up

**Comment by quasiben** [comment]
all done: https://marketing.dask.org/

**Comment by jrbourbeau** [comment]
🎉 Thanks @quasiben!!
